# Generated by Django 3.0.8 on 2020-08-18 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auto_20200816_1017'),
    ]

    operations = [
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('the_comment', models.TextField()),
                ('author', models.CharField(default='user', max_length=23)),
                ('comment_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auctions.List')),
            ],
        ),
    ]
